# Generated by Django 2.0.13 on 2019-12-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('admission', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=900)),
                ('message', models.TextField()),
            ],
        ),
    ]
